Automattic/team51-cli

src/helpers/api-helpers.php
Added a 60 sec timeout value to `@file_get_contents()` which seems to be helping me when creating deployhq configs was otherwise failing. Might need further tuning, I picked 60 seconds by random after reading comments on https://www.php.net/manual/en/function.file-get-contents.php
cc: @pippercameron
=> update deployhq API helper call

src/commands/create-development-site.php, src/helpers/api-helpers.php
Some minor refactoring to the development site creation flow.
Removed `-temporary-clone` from the naming scheme (there is a 50 char
limit in Pressable site names and this + a timestamp makes it easy to
hit that limit).
=> Allow branch specification when creating development sites.

load-application.php, src/commands/add-branch-protection-rules.php
Branch protection rules can now be added to an existing GitHub
repository with `team51
add-branch-protection-rules <repo-slug>`.
=> Branch protection rules command!

team51-cli.php
This avoids breaking the tool when a new command/class is added.
=> Regenerate autoload files.

team51-cli.php
Allows it to run correctly when the team51 command is called outside of
the root dir.
=> Pass working directory to composer.

install-osx
Fixes issue with spaces in script path by wrapping the variable output in double quotes, as per: https://yuji.wordpress.com/2011/12/28/bash-escape-spaces-in-results-of-pwd-command/
Fixes #26 
Put script in a directory with a space in the folder name.
Run `./install-osx`
Script completes without error.
=> escape script path

load-application.php, src/commands/front-create-export.php, src/commands/front-list-exports.php, src/helpers/api-helpers.php, src/helpers/config-loader.php
This PR introduces two new commands: `front-create-export` and `front-list-exports`.
The `front-create-export` creates a request with Front for an export. Exports take some time to complete so this command will only confirm that a request has been initiated. Custom timeframes are also supported with the `start-date` and `end-date` arguments.
The `front-list-exports` lists the most recent exports and their statuses in a table format. To download the export Command + Click on the filename.
The `config.json` file has been updated to include the Front token.
=> Add Front commands

composer.json
Make sure we use at least 3.0.7, which patched RSA signature issue.
=> Updating phpseclib version.

scaffold/templates/EXAMPLE-README.md, scaffold/templates/EXAMPLE-vipgoci_lint_skip_folders, scaffold/templates/EXAMPLE-vipgoci_phpcs_skip_folders, src/commands/create-repository.php
[team51-dev-requests/issues/628](https://github.com/a8cteam51/team51-dev-requests/issues/628).
Created 2 reference files to allow some plugins to skip PHPCS and PHP Lint checks.
Files created are `.vipgoci_lint_skip_folders` and `.vipgoci_phpcs_skip_folders`. 
These are just samples and don't actually skip any specific plugin, but work as a guide for the developer.
The affected command is `create-repository`, and when it finalizes executing, it would create a standard repository containing these two files in the root directory. Once created, the files' content look like this:
To test it, run `create-repository  --repo-slug [projects-name]`
=> create-repository adds 2 files to allow plugins to skip code checks

src/commands/create-development-site.php
When using the command `create-development-site` with `--temporary-clone` option, the user can now add a `--hostname` that will replace the random number at the end of the cloned site.
So for instance, instead of creating a new site `https://daily-dog-development-1631038174.mystagingwebsite.com` it can be named to `https://daily-dog-staging.mystagingwebsite.com`
**How to test**
```
team51 create-development-site --site-id=123 --branch=staging --temporary-clone --hostname=my-custom-name
```
The first commit is a full file format with no functional changes.
The actual changes for this fix are here: https://github.com/Automattic/team51-cli/commit/e3d4b3738fe0316faf120587a16aeb7d55ee6ad1
Fixes #50
=> Added --hostname option to command create-development-site

composer.lock, install-osx, src/commands/remove-user.php
Changes:
- Support for `--no-interaction` on `remove-user` command
- "wpcom" text changed to "WordPress.com & Jetpack"
- Also, update ulimit to 4096 on install process to avoid "Too many open files" error
=> Added condition for --no-interaction and updated language

src/helpers/api-helpers.php
On another convo, it was mentioned that `I tested again and am now getting a bunch of PHP Deprecated notices. FWIW, I'm using php 8.0.3.`
The exact deprecated notice:
```
$ team51-cli % team51 remove-user
Checking for updates..
There is no tracking information for the current branch.
Please specify which branch you want to merge with.
See git-pull(1) for details.
git pull <remote> <branch>
If you wish to set tracking information for this branch you can do so with:
git branch --set-upstream-to=origin/<branch> origin/add/remove-user-from-sites-command
______                                ______     _
/\__  _\                              /\  ___\  /' \
\/_/\ \/    __     __      ___ ___    \ \ \__/ /\_, \
\ \ \  /'__`\ /'__`\  /' __` __`\   \ \___``\/_/\ \
\ \ \/\  __//\ \L\.\_/\ \/\ \/\ \ …
```
=> Fixed PHP Deprecated:  Required parameter $bearer_token follows optional parameter

src/commands/create-development-site.php
Displaying more verbose pressable errors, and removing redundant site name wording, to reduce chance of hitting 50 char limit.
=> Fixing char length error

src/commands/create-repository.php
This PR removes the duplicate phpcs checks on newly created repos.
**Summary**
Duplicate folders with duplicate yml files were being created on new repos, causing the phpcs check to run twice on each commit.
**To Test**
- Create a new repository using the `create-repository` cli command. Example: `team51 create-repository --repo-slug=test-site-ok-to-delete --production-url=test-site-ok-to-delete --create-production-site` 
- Check the newly created repo. Only one `phpcs.yml` file should exist. This will be in the `.github/workflows` folder. No similar folder, such as `github/workflows`, with a `phpcs.yml` file should exist in the repo.
=> Remove duplicate phpcs checks

README.md, install-osx
This will reduce the risk of having PHP Fatal errors triggered by AMP library when  remove-user command is executed
=> Increase ulimit to 8192 bytes.

load-application.php, src/commands/plugin-list.php
Add a new command to list the installed plugins on Team 51 managed sites. 
Note: Sites must have a healthy Jetpack connection for this to work.
- From your `team51-cli` folder in a new terminal window, switch to this branch using `git checkout feature/plugin-list`.
- Test the command on your favorite Team 51 managed site, eg. `team51 plugin-list www.heyshayla.com`.
- Note the subdomain. If the site's primary domain includes the `www`, this needs to be added.
- If you receive an error, the site is most likely not Jetpack connected, our there's an issue with the connection.
=> Add feature to list plugins on a site.

src/commands/plugin-list.php
The intent of the `plugin-list` command is to mimic the wp-cli "plugin list" command - which returns the list of plugin slugs. Unfortunately, the plugin slug, or the "Text Domain" in the plugin header, is optional, and not always present. As a result, plugins with no "Text Domain" defined show as a blank line in the list of plugins. 
This PR adds a conditional to the output to use the plugin "Name" in cases where the Text Domain is empty.
This PR also sorts the plugins alphabetically, as this makes it easier to scan through the list.
=> Fix Plugin display with no slugs.

src/commands/plugin-list.php
In rare cases when a site's Jetpack connection is not healthy, the response from the call for plugin information may contain an error message. The code was attempting to display that error message for the user, however the variable name used to extract the error message was incorrect. This PR fixes the issue by setting the correct variable name.
Hmm, this is tricky. Testing requires an unstable Jetpack connection, or a recently disconnected Jetpack site. Since simulating the specific conditions for an unstable Jetpack connection is near impossible, the closest alternative would be to deactivate the Jetpack plugin on a site with a healthy connection.
Test using the command `team51 plugin-list mysite.com`. 
The result should not include any PHP error messages, and instead include the text …
=> Incorrect variable name reference in error response

.gitignore, load-application.php, src/commands/increase-ulimit, src/commands/pressable-generate-token.php, src/helpers/api-helpers.php, src/helpers/config-loader.php
This PR adds a new command `pressable-generate-token` that receives a `client_id` and `client_secret`
The full command to run is:
`team51 pressable-generate-token --client_id=ABC123 --client_secret=ABC123`, where Client ID and Client Secret are values previously created from the Pressable API Applications
The command will return not only the token, but the lines that the user will need to place on their `config.json`
Test that the token works can be a little tricky, just keep in mind the following:
- Replace `config.json` with the new token and client/secret values. These replace the email and password
- If present, remove any file called `pressable_tokens.json` from `src/helpers`, otherwise the CLI will use your old token
=> Store Pressable token in local JSON file to re-use for next call

src/commands/php-errors.php
The current `php-errors` command automatically creates a WordPress user on any site the tool tries to access. This PR limits the temporary collaborator to only SFTP access by changing the API end-point from `/sites/{site_id}/collaborators` to the `/collaborators/batch_create` end-point, [explained here](https://my.pressable.com/documentation/api/v1#collaborator-bulk-create), and no longer creates a user in wp-admin/on the site.
To make this happen, I made the following changes:
- I changed the API endpoint we were using from `sites`, to `collaborators` to be able to use the bulk creation option. This is the only option that limits access requirements, and is the key to creating a user with only SFTP Access (and not creating a user on the site). [New …
=> Stop WP User creation with php-errors command

load-application.php, src/commands/pressable-generate-token.php, src/commands/pressable-grant-access.php, src/helpers/config-loader.php
This update allows a CLI user to add a collaborator to a Pressable site.
The parameters received by the command are:
- email address
- site (which can be either a numerical site ID or a domain)
This action can be performed by a limited-access user like outside collaborators/contractors to self-provision access to Pressable sites, as long as they have a `PRESSABLE_API_REFRESH_TOKEN` defined on their config.json
Because it can be used by limited-access users, most of the constants required in config.json are now optional. If certain config key/values are missing, rather than terminating the session, the CLI will now display a warning message.
Example of how to use this command:
```
team51 pressable-grant-access --email=ecairol@gmail.com --site=esteban-sandbox.mystagingwebsite.com
```
=> Self provision access to Pressable

src/helpers/config-loader.php
Make config key DEPLOY_HQ_DEFAULT_PROJECT_TEMPLATE optional, just like the others that were recently changed.
Instead of aborting the execution, if the config key is missing it is added to a warning queue that's displayed to the user.
=> Make config key optonal, for users with limited access.

load-application.php, src/commands/pressable-call-api.php
This adds the `pressable-call-api` command, which will call the [Pressable API](https://my.pressable.com/documentation/api/v1) directly with the information passed. It doesn't validate the correctness of the API call, as that will be left up to the API.
`team51 pressable-call-api --query=<query_string> [--method=<GET|POST|PUT|DELETE] [--data=<JSON string>]`
If `--data` isn't provided, the user will be prompted. Hit enter to send an empty data object.
`--query` should be everything after `https://my.pressable.com/v1` (e.g., if you are getting the site list, you would pass `--query=sites` (`/sites` is also acceptable)
`--method` is the query method (`GET` (default), `POST`, `PUT`, `DELETE`)
`--data` is a JSON-formatted string to send as data with the request.
For example, to send [this …
=> Add command to call Pressable API

config__contractor.json, load-application.php, src/commands/jetpack-module-list.php, src/commands/jetpack-modules.php
Add a new command to list the status of all Jetpack modules on a Jetpack connected site.
Note: Sites must have a healthy Jetpack connection for this to work.
**Testing Instructions**
From your `team51-cli` folder in a new terminal window, switch to this branch using `git checkout feature/jetpack-module-list`.
Test the command on your favorite Team 51 managed site, eg. `team51 jetpack-module-list www.heyshayla.com`.
Note the subdomain. If the site's primary domain includes the `www`, this needs to be used.
If you receive an error, the site is most likely not Jetpack connected, or there's an issue with the connection.
=> Add Jetpack site module status command

load-application.php, src/commands/jetpack-module-search.php, src/commands/jetpack-module.php
Add a new command that allows a search for a specific module status and returns a list of sites with that status.
In other words, "Find all sites where the `wordads` module is currently `on`".
Note: Sites must have a healthy Jetpack connection for this to work.
- From your `team51-cli` folder in a new terminal window, switch to this branch using `git checkout feature/jetpack-module-search`.
- Test the command on your favorite Team 51 managed site, eg. `team51 jetpack-sites-with adwords on`, or, `team51 jetpack-sites-with infinite-scroll off`.
- Be warned, this process takes about 8 to 10 minutes to complete.
- As an output you should see two lists - the first is the list of sites with the module status, and the second a list of sites that could not be queried to a Jetpack connection …
=> Add Jetpack module search capability
